### PR TITLE
fix: package main path typo

### PR DESCRIPTION
**Pull request by nightink**
image

### CODE REVIEW

**Comment by nightink** [comment]
ping @bodymovin

**Comment by bodymovin** [comment]
thanks!

**Comment by nightink** [comment]
Please publish npm patch version

**Comment by edokeh** [comment]
Could ship it?

**Comment by edokeh** [comment]
Please publish it, thanks

**Comment by nightink** [comment]
@bodymovin Hi 
Your source version has been updated, but NPM has not released a version.
https://www.npmjs.com/package/lottie-api
image

**Comment by edokeh** [comment]
Please publish this :shipit:

**Comment by bodymovin** [comment]
published version 1.0.3

**Pull request merged**
