### PR TITLE
feat: add Typescript type definitions

### LINKED ISSUE #15: Typescript Definitions
Now that lottie-web has official typescript definitions, maybe we can get them created for lottie-api as well?

### PR DESCRIPTION
**Pull request by Dan-Shields**
Closes #15.

EDIT: There's many `any`'s involved when dealing with the specific layer data, but I feel defining the basic methods described in the README is better than nothing

### CODE REVIEW

**Comment by bodymovin** [comment]
thanks!

**Comment by Dan-Shields** [comment]
Thanks for merging, could you release this on npm when you get chance?

**Comment by Dan-Shields** [comment]
@bodymovin would you mind publishing a new version for this so I can start tracking it instead of my fork?

**Comment by Dan-Shields** [comment]
@bodymovin Hi Hernan, could you please look at this again? Would be an quick fix and make things a little easier!

**Pull request merged**
